<?php
/**
 * @category  Divya
 * @package   Divya\ProductTabs
 * @author    Divya - divyasekar.2894@gmail.com
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var $block \Magento\Framework\View\Element\Template */
?>

<div class="product-tab <?= $block->getData('class'); ?>">
    <?= $block->getContent(); ?>
    <?= $block->getChildHtml(); ?>
</div>
